#### Logistic Regression

In [1]:
import matplotlib.pyplot as plt
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [9]:
X = np.arange(10).reshape(-1,1)
y = np.array([0,0,0,0,1,1,1,1,1,1])

In [10]:
print(X,y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] [0 0 0 0 1 1 1 1 1 1]


In [11]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [12]:
model.fit(X,y)

LogisticRegression(random_state=0, solver='liblinear')

In [13]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(X,y)

In [15]:
model.classes_

array([0, 1])

In [16]:
model.intercept_

array([-1.04608067])

In [17]:
model.coef_

array([[0.51491375]])

In [20]:
model.predict_proba(X)

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [21]:
model.predict(X)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [22]:
model.score(X,y)

0.9

In [23]:
confusion_matrix(y, model.predict(X))

array([[3, 1],
       [0, 6]], dtype=int64)

In [24]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10



In [25]:
model = LogisticRegression(solver='liblinear', C=10,random_state=0)
model.fit(X,y)

LogisticRegression(C=10, random_state=0, solver='liblinear')

In [26]:
model.coef_

array([[1.12066084]])

In [27]:
model.intercept_

array([-3.51335372])

In [28]:
model.predict_proba(X)

array([[0.97106534, 0.02893466],
       [0.9162684 , 0.0837316 ],
       [0.7810904 , 0.2189096 ],
       [0.53777071, 0.46222929],
       [0.27502212, 0.72497788],
       [0.11007743, 0.88992257],
       [0.03876835, 0.96123165],
       [0.01298011, 0.98701989],
       [0.0042697 , 0.9957303 ],
       [0.00139621, 0.99860379]])

In [29]:
model.score(X,y)

1.0

In [30]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [32]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [33]:
X, y = load_digits(return_X_y=True)

In [35]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [40]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [41]:
model = LogisticRegression(solver='liblinear', C=0.05, random_state=0, multi_class='ovr')
model.fit(x_train, y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0,
                   solver='liblinear')

In [43]:
x_test = scaler.transform(x_test)

In [44]:
y_pred = model.predict(x_test)

In [45]:
model.score(X,y)

0.8653311074012242

In [46]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       178
           1       0.75      0.93      0.83       182
           2       1.00      0.82      0.90       177
           3       1.00      0.81      0.90       183
           4       1.00      0.68      0.81       181
           5       0.99      0.93      0.96       182
           6       0.98      0.91      0.94       181
           7       0.99      0.87      0.93       179
           8       0.50      0.98      0.66       174
           9       0.94      0.76      0.84       180

    accuracy                           0.87      1797
   macro avg       0.91      0.87      0.87      1797
weighted avg       0.92      0.87      0.88      1797



#### KNN