# Numpy

In [1]:
import numpy as np

## creating an array

In [2]:
x = [1,2,3]

In [3]:
x_np = np.array(x)

In [4]:
type(x)

list

In [5]:
type(x_np)

numpy.ndarray

In [6]:
x

[1, 2, 3]

In [7]:
x_np

array([1, 2, 3])

In [8]:
z = np.zeros(6)

In [9]:
z

array([0., 0., 0., 0., 0., 0.])

In [10]:
o = np.ones(6)

In [11]:
o

array([1., 1., 1., 1., 1., 1.])

In [12]:
e = np.empty(6)

In [13]:
e

array([1., 1., 1., 1., 1., 1.])

In [14]:
print(np.arange(0,6))
print(np.arange(1,8,2))

[0 1 2 3 4 5]
[1 3 5 7]


In [15]:
for i in np.arange(1,10,2):
    print(i)

1
3
5
7
9


## add, remove, sort

In [16]:
x = np.array([1,2,3])

In [17]:
y = np.array([4,5])

In [18]:
np.append(x,y)

array([1, 2, 3, 4, 5])

In [19]:
np.delete(x,1)

array([1, 3])

In [20]:
x = np.array([2,6,3,7,4,8,3,6,4])

In [21]:
np.sort(x)

array([2, 3, 3, 4, 4, 6, 6, 7, 8])

In [22]:
-np.sort(-x)

array([8, 7, 6, 6, 4, 4, 3, 3, 2])

## shape and size

In [23]:
x.shape

(9,)

In [24]:
x.ndim

1

In [25]:
x.size

9

In [26]:
y = np.array([[1,2],[3,4]])

In [27]:
y.shape

(2, 2)

In [28]:
y.ndim

2

In [29]:
y.size

4

## reshape

In [30]:
z = np.array([[1,2],[3,4],[5,6]])

In [31]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
z.shape

(3, 2)

In [33]:
np.reshape(z,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
z.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## dimention manipulation

In [35]:
a = np.arange(0,6)

In [36]:
a

array([0, 1, 2, 3, 4, 5])

In [37]:
a.shape

(6,)

In [38]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [39]:
a[np.newaxis].shape

(1, 6)

In [40]:
a[np.newaxis,:].shape

(1, 6)

In [41]:
a[:,np.newaxis].shape

(6, 1)

In [42]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [43]:
np.expand_dims(a,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [44]:
z.shape

(3, 2)

In [49]:
np.expand_dims(z,axis=0).shape

(1, 3, 2)

In [50]:
np.expand_dims(z,axis=1).shape

(3, 1, 2)

## indexing and slicing

### slincing array

In [51]:
x = [1,2,3,4]

In [52]:
x[1:]

[2, 3, 4]

In [53]:
num = np.arange(1,11)

In [54]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
num[6:]

array([ 7,  8,  9, 10])

In [56]:
num[:5]

array([1, 2, 3, 4, 5])

In [59]:
num[-4:]

array([ 7,  8,  9, 10])

### slicing multi dimention array

In [63]:
sample = np.array([[1,2],[3,4]])

In [66]:
sample

array([[1, 2],
       [3, 4]])

In [70]:
sample[:1]

array([[1, 2]])

In [72]:
sample[:,0]

array([1, 3])

In [76]:
sample[0,:]

array([1, 2])

### slicing by condition

In [77]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
num[num>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [80]:
condition = ((num % 2 == 0) & (num>5))
num[condition]

array([ 6,  8, 10])

### creating array from existing data

In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [84]:
np.vstack((a,b)).shape

(2, 3)

In [85]:
np.hstack((a,b)).shape

(6,)

In [90]:
c = np.arange(1,19).reshape(2,9)

In [91]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [96]:
np.hsplit(c,3)

[array([[ 1,  2,  3],
        [10, 11, 12]]),
 array([[ 4,  5,  6],
        [13, 14, 15]]),
 array([[ 7,  8,  9],
        [16, 17, 18]])]

In [97]:
d = a

In [98]:
e = a.view()

In [99]:
d

array([1, 2, 3])

In [100]:
a

array([1, 2, 3])

In [101]:
d[0] = 10

In [102]:
d

array([10,  2,  3])

In [103]:
a

array([10,  2,  3])

In [104]:
f = b.copy()

In [105]:
f

array([4, 5, 6])

In [106]:
f[0] = 10

In [107]:
f

array([10,  5,  6])

In [108]:
b

array([4, 5, 6])

## array operations

In [111]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,2],[2,2]])

In [112]:
a + b

array([[3, 4],
       [5, 6]])

In [113]:
a * b

array([[2, 4],
       [6, 8]])

In [114]:
a/b

array([[0.5, 1. ],
       [1.5, 2. ]])

In [115]:
data = np.array([[1,2,3],
                 [3,4,5],
                [4,5,6]])

In [116]:
data

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [117]:
data.shape

(3, 3)

In [119]:
data.sum(axis=1)

array([ 6, 12, 15])

In [120]:
data.sum(axis=0)

array([ 8, 11, 14])

In [121]:
data.mean(axis=0)

array([2.66666667, 3.66666667, 4.66666667])

In [124]:
np.median(data,axis=0)

array([3., 4., 5.])

In [125]:
data + np.ones((3,3))

array([[2., 3., 4.],
       [4., 5., 6.],
       [5., 6., 7.]])

## broadcasting

In [126]:
data + 2

array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8]])

In [131]:
data.min()

1

In [132]:
data.max()

6

In [133]:
data.min(axis=0)

array([1, 2, 3])

In [134]:
data.max(axis=1)

array([3, 5, 6])

## Matrix

In [135]:
m = np.random.random((3,3))

In [136]:
m

array([[0.46731526, 0.6669075 , 0.90798416],
       [0.48449454, 0.3740212 , 0.48061561],
       [0.62945538, 0.64893253, 0.07702239]])

In [143]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,5],[2,3]])

In [144]:
np.dot(a,b)

array([[ 6, 11],
       [14, 27]])

In [145]:
np.dot(a,b.T)

array([[12,  8],
       [26, 18]])

In [146]:
a

array([[1, 2],
       [3, 4]])

In [147]:
a.T

array([[1, 3],
       [2, 4]])

## exercise

In [180]:
def rgb(n):
    return np.random.randint(255, size=(3,n,n))

rgb(3)

array([[[101,  14,  74],
        [ 66,  34,  15],
        [181,  56,  10]],

       [[173, 185, 129],
        [191, 155,  39],
        [209, 103,  40]],

       [[159, 150, 124],
        [ 26,  26, 247],
        [140,  12, 121]]])

In [188]:
def rubik(n):
    return np.random.random((n,n,n))

rubik(3)

array([[[0.89418595, 0.43608051, 0.17819863],
        [0.36761943, 0.76326317, 0.99306443],
        [0.64672378, 0.51985896, 0.06394236]],

       [[0.63516968, 0.72392056, 0.77912123],
        [0.30648207, 0.53785739, 0.26815358],
        [0.76151558, 0.29725995, 0.7046673 ]],

       [[0.3138295 , 0.88915061, 0.56459503],
        [0.52656912, 0.18638445, 0.52183698],
        [0.80994973, 0.25793604, 0.1588629 ]]])

In [193]:
def split(records):
    train = records[:int(len(records)*0.8)]
    test = records[int(len(records)*0.8):]
    return train, test

In [194]:
a = np.array([[1,2,3],
             [3,5,8],
             [8,4,9]])

split(a)

(array([[1, 2, 3],
        [3, 5, 8]]),
 array([[8, 4, 9]]))

In [241]:
b = np.array([[1,0],
              [1,1])

c = np.random.random(10,2)

In [258]:
def mse(arr_2d):
    
    return np.sum((arr_2d[:,0] - arr_2d[:,1])**2)/len(arr_2d)

In [259]:
def mae(arr_2d):
    
    return np.sum(np.abs(arr_2d[:,0] - arr_2d[:,1]))/arr_2d.shape[0]

In [255]:
mse(b)

0.25

In [256]:
mae(b)

0.25

In [260]:
mse(c)

0.13385929206339928

In [261]:
mae(c)

0.308722735079877